export type Team = {
  id: string;
  name: string;
  primaryColor: string;
  secondaryColor: string;
  league: string;
  logo: Record<string, unknown>;
};

// All teams organized by league
export const allTeams: Team[] = [
  // La Liga
  {
    id: "real-madrid",
    name: "Real Madrid",
    primaryColor: "#FFFFFF",
    secondaryColor: "#00529F",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/Real Madrid.png"),
  },
  {
    id: "barcelona",
    name: "FC Barcelona",
    primaryColor: "#A50044",
    secondaryColor: "#004D98",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/FC Barcelona.png"),
  },
  {
    id: "atletico-madrid",
    name: "Atlético Madrid",
    primaryColor: "#CE3524",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/Atlético de Madrid.png"),
  },
  {
    id: "sevilla",
    name: "Sevilla FC",
    primaryColor: "#FFFFFF",
    secondaryColor: "#D4021D",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/Sevilla FC.png"),
  },
  {
    id: "real-betis",
    name: "Real Betis Balompié",
    primaryColor: "#FFFFFF",
    secondaryColor: "#00A651",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/Real Betis Balompié.png"),
  },
  {
    id: "real-sociedad",
    name: "Real Sociedad",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/Real Sociedad.png"),
  },
  {
    id: "athletic-bilbao",
    name: "Athletic Bilbao",
    primaryColor: "#DC0000",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/Athletic Bilbao.png"),
  },
  {
    id: "villarreal",
    name: "Villarreal CF",
    primaryColor: "#FFD000",
    secondaryColor: "#000000",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/Villarreal CF.png"),
  },
  {
    id: "valencia",
    name: "Valencia CF",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF8C00",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/Valencia CF.png"),
  },
  {
    id: "celta-vigo",
    name: "Celta de Vigo",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    league: "La Liga",
    logo: require("@/assets/logos/Spain - LaLiga/Celta de Vigo.png"),
  },
  // Premier League
  {
    id: "man-united",
    name: "Manchester United",
    primaryColor: "#DA291C",
    secondaryColor: "#FBE122",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Manchester United.png"),
  },
  {
    id: "liverpool",
    name: "Liverpool FC",
    primaryColor: "#C8102E",
    secondaryColor: "#00B2A9",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Liverpool FC.png"),
  },
  {
    id: "man-city",
    name: "Manchester City",
    primaryColor: "#6CABDD",
    secondaryColor: "#1C2C5B",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Manchester City.png"),
  },
  {
    id: "arsenal",
    name: "Arsenal FC",
    primaryColor: "#EF0107",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Arsenal FC.png"),
  },
  {
    id: "chelsea",
    name: "Chelsea FC",
    primaryColor: "#034694",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Chelsea FC.png"),
  },
  {
    id: "tottenham",
    name: "Tottenham Hotspur",
    primaryColor: "#FFFFFF",
    secondaryColor: "#132257",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Tottenham Hotspur.png"),
  },
  {
    id: "aston-villa",
    name: "Aston Villa",
    primaryColor: "#0B3161",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Aston Villa.png"),
  },
  {
    id: "newcastle",
    name: "Newcastle United",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Newcastle United.png"),
  },
  {
    id: "brighton",
    name: "Brighton & Hove Albion",
    primaryColor: "#0054B4",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Brighton & Hove Albion.png"),
  },
  {
    id: "fulham",
    name: "Fulham FC",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Premier League",
    logo: require("@/assets/logos/England - Premier League/Fulham FC.png"),
  },
  // Bundesliga
  {
    id: "bayern",
    name: "Bayern Munich",
    primaryColor: "#DC052D",
    secondaryColor: "#0066B2",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/Bayern Munich.png"),
  },
  {
    id: "dortmund",
    name: "Borussia Dortmund",
    primaryColor: "#FDE100",
    secondaryColor: "#000000",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/Borussia Dortmund.png"),
  },
  {
    id: "leverkusen",
    name: "Bayer Leverkusen",
    primaryColor: "#E32221",
    secondaryColor: "#000000",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/Bayer 04 Leverkusen.png"),
  },
  {
    id: "rb-leipzig",
    name: "RB Leipzig",
    primaryColor: "#DD0741",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/RB Leipzig.png"),
  },
  {
    id: "vfb-stuttgart",
    name: "VfB Stuttgart",
    primaryColor: "#FFFFFF",
    secondaryColor: "#C40C2E",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/VfB Stuttgart.png"),
  },
  {
    id: "hoffenheim",
    name: "TSG 1899 Hoffenheim",
    primaryColor: "#1C4DB7",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/TSG 1899 Hoffenheim.png"),
  },
  {
    id: "frankfurt",
    name: "Eintracht Frankfurt",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/Eintracht Frankfurt.png"),
  },
  {
    id: "freiburg",
    name: "SC Freiburg",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/SC Freiburg.png"),
  },
  {
    id: "augsburg",
    name: "FC Augsburg",
    primaryColor: "#BA0021",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/FC Augsburg.png"),
  },
  {
    id: "wolfsburg",
    name: "VfL Wolfsburg",
    primaryColor: "#37B959",
    secondaryColor: "#FFFFFF",
    league: "Bundesliga",
    logo: require("@/assets/logos/Germany - Bundesliga/VfL Wolfsburg.png"),
  },
  // Ligue 1
  {
    id: "psg",
    name: "Paris Saint-Germain",
    primaryColor: "#004170",
    secondaryColor: "#DA291C",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/Paris Saint-Germain.png"),
  },
  {
    id: "marseille",
    name: "Olympique Marseille",
    primaryColor: "#2FAEE0",
    secondaryColor: "#FFFFFF",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/Olympique Marseille.png"),
  },
  {
    id: "lyon",
    name: "Olympique Lyon",
    primaryColor: "#FFFFFF",
    secondaryColor: "#1B3F8F",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/Olympique Lyon.png"),
  },
  {
    id: "monaco",
    name: "AS Monaco",
    primaryColor: "#ED1C24",
    secondaryColor: "#FFFFFF",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/AS Monaco.png"),
  },
  {
    id: "lille",
    name: "LOSC Lille",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/LOSC Lille.png"),
  },
  {
    id: "nice",
    name: "OGC Nice",
    primaryColor: "#C91B2E",
    secondaryColor: "#000000",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/OGC Nice.png"),
  },
  {
    id: "lens",
    name: "RC Lens",
    primaryColor: "#FDB913",
    secondaryColor: "#000000",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/RC Lens.png"),
  },
  {
    id: "toulouse",
    name: "FC Toulouse",
    primaryColor: "#FFFFFF",
    secondaryColor: "#8B3030",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/FC Toulouse.png"),
  },
  {
    id: "nantes",
    name: "FC Nantes",
    primaryColor: "#FFDC00",
    secondaryColor: "#019B3E",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/FC Nantes.png"),
  },
  {
    id: "rennes",
    name: "Stade Rennais FC",
    primaryColor: "#C81828",
    secondaryColor: "#000000",
    league: "Ligue 1",
    logo: require("@/assets/logos/France - Ligue 1/Stade Rennais FC.png"),
  },
  // Serie A
  {
    id: "juventus",
    name: "Juventus FC",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/Juventus FC.png"),
  },
  {
    id: "inter",
    name: "Inter Milan",
    primaryColor: "#010E80",
    secondaryColor: "#000000",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/Inter Milan.png"),
  },
  {
    id: "ac-milan",
    name: "AC Milan",
    primaryColor: "#FB090B",
    secondaryColor: "#000000",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/AC Milan.png"),
  },
  {
    id: "napoli",
    name: "SSC Napoli",
    primaryColor: "#12A0D7",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/SSC Napoli.png"),
  },
  {
    id: "roma",
    name: "AS Roma",
    primaryColor: "#8E1F2F",
    secondaryColor: "#F0BC42",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/AS Roma.png"),
  },
  {
    id: "lazio",
    name: "SS Lazio",
    primaryColor: "#002299",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/SS Lazio.png"),
  },
  {
    id: "fiorentina",
    name: "ACF Fiorentina",
    primaryColor: "#800080",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/ACF Fiorentina.png"),
  },
  {
    id: "atalanta",
    name: "Atalanta BC",
    primaryColor: "#000000",
    secondaryColor: "#0066FF",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/Atalanta BC.png"),
  },
  {
    id: "bologna",
    name: "Bologna FC 1909",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/Bologna FC 1909.png"),
  },
  {
    id: "torino",
    name: "Torino FC",
    primaryColor: "#8B0000",
    secondaryColor: "#FFFFFF",
    league: "Serie A",
    logo: require("@/assets/logos/Italy - Serie A/Torino FC.png"),
  },
  // Liga Portugal
  {
    id: "sporting",
    name: "Sporting CP",
    primaryColor: "#006600",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/Sporting CP.png"),
  },
  {
    id: "benfica",
    name: "SL Benfica",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/SL Benfica.png"),
  },
  {
    id: "porto",
    name: "FC Porto",
    primaryColor: "#003893",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/FC Porto.png"),
  },
  {
    id: "braga",
    name: "SC Braga",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/SC Braga.png"),
  },
  {
    id: "guimaraes",
    name: "Vitória Guimarães SC",
    primaryColor: "#FFFFFF",
    secondaryColor: "#00A86B",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/Vitória Guimarães SC.png"),
  },
  {
    id: "aveiro",
    name: "CD Aves",
    primaryColor: "#1E90FF",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/Avs Futebol.png"),
  },
  {
    id: "rio-ave",
    name: "Rio Ave FC",
    primaryColor: "#008000",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/Rio Ave FC.png"),
  },
  {
    id: "estoril",
    name: "GD Estoril Praia",
    primaryColor: "#FFFFFF",
    secondaryColor: "#0066CC",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/GD Estoril Praia.png"),
  },
  {
    id: "famalicao",
    name: "FC Famalicão",
    primaryColor: "#EC1C24",
    secondaryColor: "#FFFFFF",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/FC Famalicão.png"),
  },
  {
    id: "gil-vicente",
    name: "Gil Vicente FC",
    primaryColor: "#FFCC00",
    secondaryColor: "#000000",
    league: "Liga Portugal",
    logo: require("@/assets/logos/Portugal - Liga Portugal/Gil Vicente FC.png"),
  },
];

export const leagues = [
  "All",
  "Premier League",
  "La Liga",
  "Bundesliga",
  "Serie A",
  "Ligue 1",
  "Liga Portugal",
] as const;

export const popularTeams: Team[] = [
  allTeams.find((t) => t.id === "real-madrid") ?? allTeams[0],
  allTeams.find((t) => t.id === "barcelona") ?? allTeams[1],
  allTeams.find((t) => t.id === "man-united") ?? allTeams[10],
  allTeams.find((t) => t.id === "liverpool") ?? allTeams[11],
  allTeams.find((t) => t.id === "bayern") ?? allTeams[20],
  allTeams.find((t) => t.id === "psg") ?? allTeams[30],
  allTeams.find((t) => t.id === "juventus") ?? allTeams[40],
  allTeams.find((t) => t.id === "sporting") ?? allTeams[48],
];
